- Conv2d-1
- Conv2d-5
- Conv2d-8
- Conv2d-12
- Conv2d-15
- Conv2d-19
- Conv2d-22
- Conv2d-24
- Conv2d-28
- Conv2d-31
- Conv2d-35
- Conv2d-38
- Conv2d-40
- Conv2d-44
- Conv2d-47
- Conv2d-51
- Conv2d-54
- Conv2d-56
- Conv2d-60
- Conv2d-63
- Linear-68
